'''n1,n2=int(input("enter")),int(input("enter"))
print(n1)
print(n2)
s=n1+n2
print(s)
n1,n2=int(input("enter")),int(input("enter"))
print(n1,n2)'''
a,b=(input("enter")).split(",")
print(a)
print(b)
print(int(a)+int(b))
